USE master;
DROP DATABASE IF EXISTS SocialNetwork;
CREATE DATABASE SocialNetwork;
USE SocialNetwork;
GO

CREATE TABLE Users (
   id INT IDENTITY PRIMARY KEY NOT NULL,
   name VARCHAR(50) NOT NULL,
   email VARCHAR(50) UNIQUE NOT NULL
) as NODE;

CREATE TABLE Bands (
   id INT IDENTITY PRIMARY KEY NOT NULL,
   name VARCHAR(50) NOT NULL
) as NODE;

CREATE TABLE Universities(
	id INT IDENTITY PRIMARY KEY NOT NULL ,
	name VARCHAR(100) NOT NULL,
	city VARCHAR(30) NOT NULL
) AS NODE;

CREATE TABLE Follows as EDGE
ALTER TABLE Follows
ADD CONSTRAINT EC_Follows CONNECTION (Users TO Users);

CREATE TABLE BasedIn (year INT) as EDGE
ALTER TABLE BasedIn
ADD CONSTRAINT EC_BasedIn CONNECTION (Bands TO Universities);

CREATE TABLE PlaysIn as EDGE
ALTER TABLE PlaysIn
ADD CONSTRAINT EC_PlaysIn CONNECTION (Users TO Bands);

